### ISSUE TITLE
Something wrong with the Algorithms declaration in README

### ISSUE THREAD

**Issue by Jokeren** [LPD-EPFL/ASCYLIB#11]
As far as I know, the Howley tree is the first lock-free(non-blocking) internal BST, while in `README` it is claimed as lock-based.

I don't know whether I missed something?

**Comment by trigonak** [comment]
Hi, you are absolutely right. This error was a typo (omission), we are really sorry for that. 
Thanks for bringing this mistake to our attention.
We will double check the correctness of the table.
