### ISSUE TITLE
undocumented algorithms

### ISSUE THREAD

**Issue by ryuxin** [LPD-EPFL/ASCYLIB#18]
Thanks for releasing such a great project.
In the `src` directory, I find some undocumented algorithms.
Those following are not list in the table in `README`.
```
/src/linkedlist-lazy_orig/
/src/linkedlist-lazy_cache/
/src/linkedlist-lazy_sp/
/src/skiplist-pugh-string/
/src/stack-optik1/
/src/stack-optik2/
/src/queue-hybrid/
/src/queue-optik2a/
/src/queue-optik4/
/src/queue-optik5/
```
Could you add some explanation for those code?
Additional question:
What is the `lock` file in some directories? How to use it? (such as `src/linkedlist-lazy/lock`)
Thanks a lot!

**Comment by trigonak** [comment]
Hello. 

Thanks for the comment. Sorry for my terribly late reply. I didn't reply immediately and then....

Indeed, these algorithms are not documented. Most of the were just attempts to create/optimize something new. In brief here (I will eventually document the ones that are worth documenting):

- `/src/linkedlist-lazy_orig/` the original lazy list algorithm, as described in the paper that introduced it
- `/src/linkedlist-lazy_cache/` the lazy list algorithm, with the caching optimization (described in the OPTIK paper)
- `/src/linkedlist-lazy_sp/` the lazy algorithm, optimized using sequential proximity (https://infoscience.epfl.ch/record/229339)
- `/src/skiplist-pugh-string/` an effort to add string support to Pugh's skiplist
- `/src/stack-optik1/`, `/src/stack-optik2/` trying OPTIK in stacks
- `/src/queue-hybrid/` MS-queue with operation lock-free and the other lock-based
- `/src/queue-optik2a/`, `/src/queue-optik4/`, `/src/queue-optik5/` trying OPTIK in queues

I'm not sure what are these lock files. I don't believe they should be there. Thanks for the catch :-)

**Comment by winterNan** [comment]
Hi, 
    Are ASCYLIB in general a set of micro-benchmarks or do they indeed represent real-world workloads?
    I am new to the benchmarks and want to know a bit of the big picture. 
    Thanks!

**Comment by trigonak** [comment]
Hi there,

These are microbenchmarks only. 

Vasilis.
