### ISSUE TITLE
About your implementations

### ISSUE THREAD

**Issue by Jokeren** [LPD-EPFL/ASCYLIB#8]
Hi, all!

This project is wonderful, I have been searching for a concurrency library implemented in `C` for long time. Before I find this project, I study the code from "the art of multiprocessor programming", while all of them are in Java. 

But questions still left, one is that have you implemented all the features from the paper?

For example, I read Bronson's practical concurrent BST. I find that he has incorporated "fast clone" technique, but I cannot find a similar one in your code. 

The other thing is about your correctness testing program, can you explain what's the idea behind the code?

Thank you very much!

**Comment by trigonak** [comment]
Hi there,

Thanks for your comment and interest :)
Regarding your first question, we have not implemented the "fast clone" feature of Bronson's tree.
We focused this work on the basic search-data-structure interface: search, insert, and delete.
Feel free to implement any features you are interested in and make a push request in ASCYLIB.

Regarding `test_correct.c`, it is a very simple test that checks (i) the atomicity of reading the key/value pairs, and (ii) the correctness of the garbage collection (`ssmem`). In short, every insertion puts a a `key` and a pointer to a `val`, where the pointed memory contains the `key` as the value. The search and remove operations get the pointed memory for that `key` and check if `key == *val`. If the memory was re-used before it is safely garbage collected, errors would appear.
